name: .NET Publish and Deploy to AWS EC2

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET 8.0.x
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # Step 3: Restore dependencies and publish the project
      - name: Publish .NET project
        run: |
          dotnet restore
          dotnet publish -c Release -o ./publish
        working-directory: backend

      # Step 4: Copy published files to AWS EC2 instance
      - name: Copy files to EC2 via SSH
        env:
          SSH_KEY: ${{ secrets.SU_PW }} # SSH key stored in GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -r ./backend/publish ec2-user@ec2-13-60-78-69.eu-north-1.compute.amazonaws.com:app

      # Step 5: Update environment variables in the systemd service file
      - name: Update environment variables
        env:
          SSH_KEY: ${{ secrets.SU_PW }} # SSH key stored in GitHub Secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        run: |
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-60-78-69.eu-north-1.compute.amazonaws.com "sudo bash -c 'echo -e \"\n\
          Environment=AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID\n\
          Environment=AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY\n\
          Environment=CLERK_SECRET_KEY=$CLERK_SECRET_KEY\n\
          Environment=STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY\n\
          Environment=VERCEL_TOKEN=$VERCEL_TOKEN\n\
          Environment=SMTP_PASSWORD=$SMTP_PASSWORD\n\
          Environment=CONNECTION_STRING=$CONNECTION_STRING\n\
          \" >> /etc/systemd/system/backend.service'"

      # Step 6: Restart the .NET app on the EC2 instance
      - name: Restart .NET app
        env:
          SSH_KEY: ${{ secrets.SU_PW }} # SSH key stored in GitHub Secrets
        run: |
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-60-78-69.eu-north-1.compute.amazonaws.com "sudo systemctl restart backend.service"
