on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - run: dotnet publish -c Release -o publish
        working-directory: backend

      - name: Add SSH Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 172.232.147.147 >> ~/.ssh/known_hosts

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Install rsync and Verify Installation
        run: |
          sudo apt-get -y install rsync openssh-client

      - name: Deploy Dotnet App
        run: /usr/bin/rsync -rlDvz --delete ./backend/publish/ wilhelm@172.232.147.147:/var/www/restaurantbackend/

      - name: Set AWS Environment Variables
        env:
          SUDO_PASSWORD: ${{ secrets.SU_PW }}
        run: |
          ssh -o StrictHostKeyChecking=no wilhelm@172.232.147.147 "
            echo $SUDO_PASSWORD | sudo -S bash -c '
            mkdir -p /etc/systemd/system/restaurantbackend.service.d/
            echo \"[Service]
            Environment=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            Environment=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            Environment=CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
            Environment=STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            Environment=VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}
            Environment=SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            Environment=CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
            \" > /etc/systemd/system/restaurantbackend.service.d/aws-env.conf
            systemctl daemon-reload
            '
          "

      - name: Restart service on CentOS server
        env:
          SUDO_PASSWORD: ${{ secrets.SU_PW }}
        run: |
          ssh -o StrictHostKeyChecking=no wilhelm@172.232.147.147 "
            echo $SUDO_PASSWORD | sudo -S systemctl restart restaurantbackend.service
           "
